yesodweb/yesodweb.com-content

- book/asciidoc/scaffolding-and-the-site-template.asciidoc
There is a typo in the Scaffolding chapter of the book.
It refers to portion of the cabal file as "exported-modules".
The real name of this section is "exposed-modules".
This commit changes the only mention of "exported-modules" in the chapter.
> Book: Change "exported-modules" to "exposed-modules"

- blog/2013/01/adding-css-js.md
- blog/2013/02/ajax-with-scaffold.md
- blog/2013/02/authentication-for-testing.md
- homepage.html
- page/community.html
Related to this: https://github.com/yesodweb/yesod/issues/1070
The big changes in `homepage.html` is because of Windows file encoding
which is now saved in a UNIX format.
> Change cookbook link

- book/asciidoc/scaffolding-and-the-site-template.asciidoc
I couldn't find `persistFile` function:
https://www.stackage.org/lts-3.12/hoogle?q=persistFile
so I concluded that `persistFileWith` is meant.
> Fix typo ‘persistFile’ → ‘persistFileWith’

- book/asciidoc/haskell.asciidoc
This allows running the SQL joins examples without further installation.
> Add esqueleto to built libraries

- book/asciidoc/authentication-and-authorization.asciidoc
This will prevent
```
Example.hs:89:27: Warning:
In the use of ‘conduitManagerSettings’
(imported from Network.HTTP.Conduit):
Deprecated: "Use tlsManagerSettings"
```
> Update function to use tlsManagerSettings

- book/asciidoc/authentication-and-authorization.asciidoc
Following the email registration example, I have no email server on my local (best way to prevent accidental emails :wink: ) - but I still wanted to see the `verurl` one gets.
This PR is an attempt at adding the `verurl` to the console. I assume there's a better way to print, but `liftIO $ print "Copy/ Paste this URL in your browser:" $ unpack verurl` doesn't seem to work.
> Print out to the console the verification email

- page/quickstart.md
Because the page under old url says that the page has been moved. So we prevent the user for a further click.
> Fixed stack download url in quickstart

- book/asciidoc/routing-and-handlers.asciidoc
The comment after the redirect from Link1 to Link2 was incorrect. The link text in the home handler has also been changed to read "redirect chain" instead of "redirect loop" since it's not really a loop.
> Fix typo in hash fragments example.

- book/asciidoc/deploying-your-webapp.asciidoc
#140
Recommend stack as the preferred way of developing with Yesod and link to quickstart guide. Also update the Compiling section to reflect stack recommendation. The reference to `yesod keter` automatically calling `cabal clean` has also been removed since there is no other mention of cabal on the page.
> Mention stack as the preferred development tool.

- page/quickstart.md
because we run `yesod devel` as `stack exec -- yesod devel` i don't believe we need to actually install `yesod-bin` and others into the global system.
if this is wrong, feel free to reject.
if not, maybe the language should also change to be clear that while it looks like we're just building these libs, we actually get the executables as well.
> install -> build

- book/asciidoc/http-conduit.asciidoc
The haskell-lang.org link supersedes the Jump Project link because the Jump Project is over.
> Use superseding link about http-client

- book/asciidoc/shakespearean-templates.asciidoc
I think the issue at found the issue at https://github.com/yesodweb/yesodweb.com-content/issues/88 is similar to mine.
Ran into similar issue, 
```
$ stack runghc test.hs 
test2.hs:20:12: error:
• Exception when trying to run compile-time code:
"-- @template.lucius
foo { bar: baz }" (line 1, column 1):
unexpected " "
expecting "-->"
CallStack (from HasCallStack):
error, called at ./Text/Css.hs:136:17 in shakespeare-2.0.12.1-7zylhH6EvxxByWoabG0aiC:Text.Css
Code: luciusFileDebug "template.lucius"
• In the untyped splice: $(luciusFileDebug "template.lucius")
```
> Fixes user error of pasting commented line in .lucius file

- book/asciidoc/yesod-for-haskellers.asciidoc
```
• The constructor ‘YesodRunnerEnv’ should have 5 arguments, but has been given 4
• In the pattern: YesodRunnerEnv _logger site _sessionBackend _
In an equation for ‘yesodDispatch’:
yesodDispatch
(YesodRunnerEnv _logger site _sessionBackend _)
_req
sendResponse
= sendResponse
$ responseBuilder
status200
[("Content-Type", "text/html")]
(renderHtmlBuilder $ welcomeMessage site)
In the instance declaration for ‘YesodDispatch App’
|
29 |   yesodDispatch (YesodRunnerEnv _logger site _sessionBackend _) _req sendResponse =
|                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
> fix compile error

- book/asciidoc/shakespearean-templates.asciidoc
This explanation should clarify the the issue in
https://github.com/yesodweb/shakespeare/issues/217
about ^{..} syntax in Text.Shakespeare.Text
> Added explanation for variable interpolation for "Other Shakespeare"

- book/asciidoc/wiki-chat-example.asciidoc
- book/generated-xml/wiki-chat-example.xml
[eventSourceAppChan](https://www.stackage.org/haddock/lts-11.9/wai-extra-3.0.22.0/src/Network.Wai.EventSource.html#eventSourceAppChan) already duplicates argument Chan.
> No need to duplicate another time

- book/asciidoc/persistent.asciidoc
Link to 'Persistent Entity Syntax' documentation in the Persistent chapter of the book was out of date. Updated to point to the correct page. Also updated documentation link at the end of the chapter.
> Updated link to Persistent Entity Syntax documentation

- book/asciidoc/persistent.asciidoc
Based off of a discussion with @bitemyapp in the Haskell Slack channel, added disclaimer to not use automated database migrations in production environments.
> Added warning about not using automated migrations in production

- blog/2010/9/yo-dawg-template-haskell.html
HTTP sources are being blocked, as the blog is served up by HTTPS.
> Use https url to gist

- book/asciidoc/blog-example-advanced.asciidoc
Current blog example does not compile because it uses deprecated Persona/BrowserID modules. This changes
> Change blog example auth from BrowserID to OpenID

- book/asciidoc/authentication-and-authorization.asciidoc
Maybe I'm misunderstanding [the api docs](https://www.stackage.org/haddock/lts-13.25/yesod-auth-1.6.6/Yesod-Auth-Email.html#v:verifyAccount) but this seems to be what they suggest. See also yesodweb/yesod-cookbook#44.
> book/auth: reset verkey in verifyAccount

- book/asciidoc/authentication-and-authorization.asciidoc
Updated the example code to be in line with current version of the Network.Mail.Mime library as per http://hackage.haskell.org/package/mime-mail-0.5.0/docs/Network-Mail-Mime.html#t:Part
> Fix broken use of Network.Mail.Mime

- book/asciidoc/authentication-and-authorization.asciidoc
insertBy left and right were switched around, the opposite of https://hackage.haskell.org/package/persistent-2.10.1/docs/src/Database.Persist.Class.PersistUnique.html#insertBy
> Fix reversed explanation on insertBy

- book/asciidoc/scaffolding-and-the-site-template.asciidoc
The current scaffolding example uses an old resolver for GHC 8.4.4. This updates it to use the same scaffold example (except retaining postgres) as the quick start guide.
> update outdated scaffolding command

- book/asciidoc/internationalization.asciidoc
Since i18n was removed from scaffolding this documentation also needs an update.
I tried to describe the prozess of adding it back to scaffolding as explained [here](https://github.com/yesodweb/yesod/wiki/i18n-messages-in-the-scaffolding).
> Updated internationalization.asciidoc

- book/asciidoc/wiki-chat-example.asciidoc
Fixes https://github.com/yesodweb/yesodweb.com-content/issues/259.
> Fix mismatch between text and code example in the Wiki chat example

- book/asciidoc/shakespearean-templates.asciidoc
- book/generated-xml/shakespearean-templates.xml
I believe the type class that we need to be referencing is [ToMarkup](https://www.stackage.org/haddock/lts-16.26/blaze-markup-0.8.2.7/Text-Blaze.html#t:ToMarkup). This would be consistent with the rest of the document's mention of `blase-html`.
P.S. I think the reason for the error is that we have a type synonym `type Html = Markup`
> Replace `ToHtml` with `ToMarkup`

- book/asciidoc/internationalization.asciidoc
- book/asciidoc/routing-and-handlers.asciidoc
- book/asciidoc/sql-joins.asciidoc
- book/asciidoc/yesod-for-haskellers.asciidoc
As of GHC 9.0.1, the mkYesod splice needs to be before the Yesod instance.
> Move splices before instance declarations

- book/asciidoc/yesod-typeclass.asciidoc
I tried regenerating the docs, but it's crashing for me:
$ book/tools/generate.sh
...
+ [[ /home/jeremy/src/github.com/yesodweb/yesodweb.com-content/book/tools/../asciidoc/yesod-typeclass.asciidoc -nt /home/jeremy/src/github.com/yesodweb/yesodweb.com-content/book/tools/../generated-xml/yesod-typeclass.xml ]]
+ asciidoc -b docbook45 --attribute=idprefix=yesod-typeclass_ -o tmp /home/jeremy/src/github.com/yesodweb/yesodweb.com-content/book/tools/../asciidoc/yesod-typeclass.asciidoc
+ /home/jeremy/src/github.com/yesodweb/yesodweb.com-content/book/tools/strip-article-info.hs tmp
Could not parse '/home/jeremy/.stack/global-project/stack.yaml':
AesonException "Error in $.resolver: failed to parse field 'resolver': failed to parse field resolver: failed to parse field 'name': key \"name\" not …
> Fix documentation about default value of approot

- book/asciidoc/persistent.asciidoc
This change makes it so that the full examples in the `persistent` chapter compile under GHC 9.2.5.
> Bring full `persistent` examples up-to-date

- book/asciidoc/routing-and-handlers.asciidoc
Hi there, I recently stumbled upon the question how Yesod handles empty strings like in `@{MyRouteR ""}`.
First, the behavior was quite irritating for me, then I understood the logic behind.
I documented it and thought it might fit well in the book chapter on routes?
What do you think?
In my case, I deliberately wanted pass `""` in `/orders/#Text`. I wanted to use query string args – submitted through a form with `method=get` – to redirect from `/orders/-?order_number=123456` to `/orders/123456`.
> Add documentation for special case of empty args

- book/asciidoc/persistent.asciidoc
I'm getting the following error when building the Person code snippet. Adding the recommended two lines makes the program compile on my system.
```
derek persistent-demo % stack build
Warning: Stack has not been tested with GHC versions above 9.6, and using 9.6.4, this may fail.
Warning: Stack has not been tested with Cabal versions above 3.10, but version 3.10.1.0 was found, this may fail.
persistent-demo> configure (lib + exe)
Configuring persistent-demo-0.1.0.0...
persistent-demo> build (lib + exe)
Preprocessing library for persistent-demo-0.1.0.0..
Building library for persistent-demo-0.1.0.0..
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_persistent_demo
Preprocessing executable 'persistent-demo-exe' for persistent-demo-0.1.0.0..
Building executable 'persistent-demo-exe' for …
```
> Update Persistent language extensions in Person table code example
